### ISSUE TITLE
Persist config on changed settings 

### ISSUE THREAD

**Issue by rockymontana** [29th/forums#5]
Hello.
I'm trying to use the concept of your solution, but I run into the issue that the config.php file doesn't get written to when I deploy my own copy of it into the container. I do set the conf-dir and all the files within it to 777 so it is writable by the application. Weirdest thing is that if I let Vanilla create the config.php on its own the application do write to it, but only then.

Have you run into any issues like this?
Thanks!

**Comment by wilson29thid** [comment]
Hi @rockymontana it's been a while since I've worked with this, but I'm happy to try and help.

This repo is designed for config.php to be version controlled. So you should modify the file, then run `docker build` and deploy the built image. If you change the config from the vanilla dashboard, it will modify config.php in the running container, but those changes won't be persisted to disk (deliberately).

Can you elaborate on your setup (e.g. how you're deploying it) and what you're trying to change and how?

**Comment by rockymontana** [comment]
So we deploy our vanilla forum with rancher, and it spins up and everything is fine and dandy.
My issue isn't persisting the config file between container restarts, but rather writing to the config.php in the spinning container. If I let Vanilla create the config (e.g running the setup) the config file can get written to, but if use a config from our vcs and make it writable, it refuses to write to the config. So if I go into my setting and change literally anything - the settings won't get saved when I refresh the page.
It's like vanilla has to create the file on it's own to want to write to it.

I thought that maybe it could have something to do with the UPDATE_TOKEN or COOKIE_SALT keys, but I get the same behavior when I set those as env vars and use them in bootstrap.early.php

Did you have any issues like this when you created your solution?

**Comment by rockymontana** [comment]
Thanks for the willingness to help btw. Really appreciate it 👍

**Comment by wilson29thid** [comment]
Hm, that’s odd.. it doesn’t ring a bell. Do the php/apache logs say anything about a file write error? Any chance you’re _mounting_ config.php as a volume with read-only permissions?

Here is how we run the container in prod (no volumes except uploads folder): https://github.com/29th/personnel/blob/master/docker-compose.prod.yml

Only other thing I can think of is that some config in vanilla is in the database..maybe it has something to do with the config setting of whether or not setup has been run. But I’m reaching there.

**Comment by rockymontana** [comment]
Hello Wilson. Sorry for not reaching back to you the past week. Been busy with other stuff at work.
I'm starting to give up on my solution and think that it must have something to do with my docker-setup.
I'm quite the rookie when it comes to docker, so it's most likely so ;)

My apache logs doesn't say anything at all. I'm gonna try and replicate your config now instead.
